apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - image: mysql
    name: mysql
    command: ["sh", "-c", "env"]
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
  restartPolicy: Never
status: {}
