apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - image: nginx
    name: web
    ports:
      - containerPort: 80
    volumeMounts:
      - name: config-vol
        mountPath: /usr/share/nginx/html
  restartPolicy: Never
  volumes:
  - name: config-vol
    configMap:
      name: html-content
    
