apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  containers:
  - image: busybox
    name: config-demo
    command: ["sh", "-c", "env"]
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_MODE
  restartPolicy: Never
status: {}
