apiVersion: v1
kind: Pod
metadata:
  labels:
    run: limit
  name: limit
spec:
  containers:
  - image: nginx
    name: limit
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  restartPolicy: Never
  priorityClassName: low
