apiVersion: v1
kind: Pod
metadata:
  labels:
    run: twocontainers
  name: twocontainers
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: container1
  - name: container2
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
